### PR TITLE
Aggregated various testing_utils around into a single module.

### PR DESCRIPTION
**Pull request by stefanoborini**

### CODE REVIEW

**Comment by kitchoi** [comment]
Thanks @stefanoborini !
There are a couple examples in /examples that probably need fixing too.

**Comment by stefanoborini** [comment]
I think they are already fixed. let me recheck if it's all we need.

**Comment by kitchoi** [comment]
Ah you are right.  LGTM.  Thanks!

**Comment by kitchoi** [comment]
@stefanoborini Good to merge :+1:

**Pull request merged**
