### PR TITLE
[WIP] Refactor show, snapshot and exposed add_dataset function to plugin

### PR DESCRIPTION
**Pull request by kitchoi**
- [x] Expose the `add_dataset` function as a shortcut to setting up a CUDS Source for `mlab.pipeline.add_dataset`.
- [x] Add `add_default_modules`.

Refs: #134

Usage:

```
from simphony.visualisation import mayavi_tools
source = mayavi_tools.add_dataset(cuds, point_scalars_name="TEMPERATURE")  # scene is empty
mayavi_tools.add_default_modules(source)   # add default visualisation
```

`show` is doing exactly the above + `mlab.show()`
Usage for `show` (similarly for `snapshot`):

```
from simphony.visualisation import mayavi_tools
mayavi_tools.show(cuds, point_scalars_name="TEMPERATURE", point_vectors_name="VELOCITY")

# if "TEMPERATURE" and "VELOCITY" are the only point scalars and vectors, 
# previous behaviour works fine
mayavi_tool.show(cuds)
```
- [ ] Need to update documentation

@itziakos, @dpinte what do you think?

After this PR is accepted and merged, I will create a new issue for making the GUI use these functions instead.

### CODE REVIEW

**Comment by kitchoi** [comment]
Relevant to #132 too

**Comment by kitchoi** [comment]
@dpinte, @itziakos, this is ready for review.  Please let me know if this is good to merge.

**Comment by kitchoi** [comment]
`add_dataset` may not be ideal.  Let me try a different implementation for refactoring.

**Comment by dpinte** [comment]
@kitchoi LGTM

**Comment by kitchoi** [comment]
Superseded by #162, closing.

**Pull request closed without merging**
