### PR TITLE
Fix bug for CUBA.LATTICE_VECTORS in cuba_data_accumulator

### LINKED ISSUE #135: LATTICE_VECTORS causes cuba_data_accumulator to error
This will give AssertionError in tvtk

```
from simphony.cuds.particles import Particles
from simphony.testing.utils import create_particles
from simphony.core.cuba import CUBA
from simphony.visualisation import mayavi_tools

particles = create_particles() # restrict=[CUBA.LATTICE_VECTORS])
cuds = Particles("test")
cuds.add_particles(particles)

mayavi_tools.show(cuds)
```

That is because in `cuba_data_accumulator.load_onto_vtk`:

```
default = dummy_cuba_value(cuba)  # cuba = CUBA.LATTICE_VECTORS for this bug
...
   elif isinstance(default, numpy.ndarray) and len(default) == 3:
       # do stuff for vector values
```

shape of LATTICE_VECTORS is [3, 3], `default` is a 3x3 array and so `len(default) == 3` and it is mistaken as a vector.

### PR DESCRIPTION
**Pull request by kitchoi**
fix #135

### CODE REVIEW

**Comment by kitchoi** [comment]
strange this has not triggered CI build

**Comment by kitchoi** [comment]
@dpinte please take a look.

**Comment by kitchoi** [comment]
`LATTICE_VECTORS` is not a support CUBA key to begin with, so an alternative implementation would be check against `supported_cuba` soon after [for cuba in self.keys:](https://github.com/simphony/simphony-mayavi/blob/fix-cuba-data-accumulator/simphony_mayavi/core/cuba_data_accumulator.py#L131)

**Comment by dpinte** [comment]
@kitchoi LGTM

**Pull request merged**
