### PR TITLE
EngineFactory class

### PR DESCRIPTION
**Pull request by kitchoi**
- [x] Refactor factory functions to Traits class
- [x] Use the extension names from simphony.engine
- [x] Delayed import until a new engine wrapper is requested
- [x] Need more tests for engine_wrapper.api

User experience would be similar

_Before (master)_:
old

_After (this branch)_:
new
new2

### CODE REVIEW

**Comment by kitchoi** [comment]
@itziakos How about this? :)

**Comment by itziakos** [comment]
- Please remove the load engine from py file.

**Comment by kitchoi** [comment]
Mmmmmm I thought that was desired.

**Comment by itziakos** [comment]
UI: It is not necessary to use the word `factory` in the ui labels. Just `Engines` or `Registered Engines` should be enough.

**Comment by kitchoi** [comment]
It would be more elegant to simply name "registered engine", but I personally think the word "create from factory" highlights the fact that a new instance is being created.  I am not sure how obvious the implication would be without explicitly saying so.

**Comment by kitchoi** [comment]
On second thought, maybe "factory" means nothing to non-developers.  Ah I am biased, so I don't know.  I think you're right.  But I also think the word "create" should be kept.

**Comment by kitchoi** [comment]
This is how it looks now.
renamed

I think we should keep the "load from *.py" for now because it is useful (and it is in the master already).  To use the Mayavi's "run script" function and retrieve a local variable from there needs some more work.

**Comment by kitchoi** [comment]
actually, I couldn't do meaningful tests for the engine factory api because 
(1) i would be patching the non-existing modules with ones that most definitely create a ABCModelingEngine instance.
(2) stevedore extensions is hard to fake, it may be possible, but I haven't found out how.

**Comment by kitchoi** [comment]
I think at the moment I'd better move on to other issues.
Please let me know if this is good to merge, @itziakos

**Comment by kitchoi** [comment]
@itziakos, could this be merged and I implement the removal of load-from-py #138 in a separate PR?

**Pull request merged**
